-- ============================================================
-- SUPABASE DATABASE SCHEMA FOR MOBENG ALL IN 1 STORE
-- Run this SQL in Supabase Dashboard -> SQL Editor
-- ============================================================

-- 1. TABLE: complaints (Termasuk kolom penanganan komplain baru)
CREATE TABLE IF NOT EXISTS public.complaints (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tanggal DATE NOT NULL,
    merek_kendaraan TEXT NOT NULL,
    model_kendaraan TEXT NOT NULL,
    jenis_pekerjaan_sebelumnya TEXT DEFAULT '',
    jenis_complain TEXT NOT NULL,
    keterangan TEXT DEFAULT '',
    status TEXT DEFAULT 'Open',
    pic TEXT DEFAULT '',
    penyebab_masalah TEXT DEFAULT '',
    catatan_penanganan TEXT DEFAULT '',
    store_name TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Apabila tabel 'complaints' sudah ada sebelumnya, jalankan ALTER TABLE berikut untuk menambahkan kolom-kolom baru:
ALTER TABLE public.complaints ADD COLUMN IF NOT EXISTS jenis_pekerjaan_sebelumnya TEXT DEFAULT '';
ALTER TABLE public.complaints ADD COLUMN IF NOT EXISTS pic TEXT DEFAULT '';
ALTER TABLE public.complaints ADD COLUMN IF NOT EXISTS penyebab_masalah TEXT DEFAULT '';
ALTER TABLE public.complaints ADD COLUMN IF NOT EXISTS catatan_penanganan TEXT DEFAULT '';

-- RLS & Access Policy (Opsional jika RLS diaktifkan)
ALTER TABLE public.complaints ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read complaints" ON public.complaints FOR SELECT USING (true);
CREATE POLICY "Allow public insert complaints" ON public.complaints FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update complaints" ON public.complaints FOR UPDATE USING (true);
CREATE POLICY "Allow public delete complaints" ON public.complaints FOR DELETE USING (true);


-- 2. TABLE: sales_entries
CREATE TABLE IF NOT EXISTS public.sales_entries (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tanggal DATE NOT NULL,
    merek_kendaraan TEXT NOT NULL,
    model_kendaraan TEXT NOT NULL,
    tahun_kendaraan TEXT DEFAULT '',
    jenis_pekerjaan TEXT NOT NULL,
    jumlah_sales NUMERIC NOT NULL DEFAULT 0,
    leadtime_jam INT DEFAULT 0,
    leadtime_menit INT DEFAULT 0,
    special_tools TEXT DEFAULT '',
    langkah_pengerjaan TEXT DEFAULT '',
    store_name TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.sales_entries ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read sales_entries" ON public.sales_entries FOR SELECT USING (true);
CREATE POLICY "Allow public insert sales_entries" ON public.sales_entries FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update sales_entries" ON public.sales_entries FOR UPDATE USING (true);
CREATE POLICY "Allow public delete sales_entries" ON public.sales_entries FOR DELETE USING (true);


-- 3. TABLE: monthly_reports
CREATE TABLE IF NOT EXISTS public.monthly_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bulan INT NOT NULL,
    tahun INT NOT NULL,
    penjelasan_performa TEXT DEFAULT '',
    kendala TEXT DEFAULT '',
    action_plan TEXT DEFAULT '',
    total_sales_toko NUMERIC DEFAULT 0,
    store_name TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    CONSTRAINT monthly_reports_bulan_tahun_store_unique UNIQUE (bulan, tahun, store_name)
);

ALTER TABLE public.monthly_reports ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read monthly_reports" ON public.monthly_reports FOR SELECT USING (true);
CREATE POLICY "Allow public insert monthly_reports" ON public.monthly_reports FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update monthly_reports" ON public.monthly_reports FOR UPDATE USING (true);
CREATE POLICY "Allow public delete monthly_reports" ON public.monthly_reports FOR DELETE USING (true);


-- 4. TABLE: store_targets
CREATE TABLE IF NOT EXISTS public.store_targets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_name TEXT NOT NULL,
    tahun INT NOT NULL,
    target_amount NUMERIC NOT NULL DEFAULT 650000000,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    CONSTRAINT store_targets_store_tahun_unique UNIQUE (store_name, tahun)
);

ALTER TABLE public.store_targets ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read store_targets" ON public.store_targets FOR SELECT USING (true);
CREATE POLICY "Allow public insert store_targets" ON public.store_targets FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update store_targets" ON public.store_targets FOR UPDATE USING (true);
CREATE POLICY "Allow public delete store_targets" ON public.store_targets FOR DELETE USING (true);


-- 5. TABLE: capability_maps
CREATE TABLE IF NOT EXISTS public.capability_maps (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    store_name TEXT NOT NULL UNIQUE,
    jobs JSONB DEFAULT '[]'::jsonb,
    rows JSONB DEFAULT '[]'::jsonb,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.capability_maps ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read capability_maps" ON public.capability_maps FOR SELECT USING (true);
CREATE POLICY "Allow public insert capability_maps" ON public.capability_maps FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update capability_maps" ON public.capability_maps FOR UPDATE USING (true);
CREATE POLICY "Allow public delete capability_maps" ON public.capability_maps FOR DELETE USING (true);

